services:
  busbot:
    build: .
    container_name: busbot
    restart: unless-stopped
    env_file: .env
    volumes:
      - busbot-data:/app/data
      - ./:/app/data
      - ./user_config.json:/app/data/user_config.json
volumes:
  busbot-data:
